name: Update Files (Version)

on:
  release:
    types:
      - created
      
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.UPDATE_TOKEN }}
          ref: main
          
      - name: Update files
        uses: MathieuSoysal/file-updater-for-release@v1.0.3
        with:
          files: README.md, main.py
          prefix: "v"
